### ISSUE TITLE
type object not subscriptable error with Python3.8 

### ISSUE THREAD

**Issue by lucask07** [PhysioLabXR/PhysioLabXR#120]
I received the error below when installing in a conda environment with Python3.8. This error did not occur with Python3.10.

```
  File "/Users/koer2434/opt/anaconda3/envs/phys2/lib/python3.8/site-packages/physiolabxr/presets/Presets.py", line 14, in <module>
    from physiolabxr.presets.GroupEntry import GroupEntry
  File "/Users/koer2434/opt/anaconda3/envs/phys2/lib/python3.8/site-packages/physiolabxr/presets/GroupEntry.py", line 12, in <module>
    from physiolabxr.utils.dsp_utils.dsp_modules import *
  File "/Users/koer2434/opt/anaconda3/envs/phys2/lib/python3.8/site-packages/physiolabxr/utils/dsp_utils/dsp_modules.py", line 344, in <module>
    def run_data_processors(data, data_processor_pipeline: list[DataProcessor]):
TypeError: 'type' object is not subscriptable
```

**Comment by ApocalyVec** [comment]
Hey @lucask07, thank you for pointing this out. Yes indeed subscription in type is only added in Python 3.9+ as per [the version notes here](https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections), and [the discussion](https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python) here. 

We updated the note on Python versions in the docs: [install with pip](https://physiolabxrdocs.readthedocs.io/en/latest/#install-with-pip), and [run from source](https://physiolabxrdocs.readthedocs.io/en/latest/Contribute.html#run-from-source).

**Comment by ApocalyVec** [comment]
Closing this issue setting the minimal requirements for PhysioLabXR to be Python 3.9
